### PR TITLE
Add support for route-middleware

### PR DESCRIPTION
**Pull request by grncdr**
Title says it all

### CODE REVIEW

**Comment by polidore** [comment]
agree. this seems like a good change.

**Comment by JasonMiesionczek** [comment]
I think this is somewhat essential for securing routes, unless there are other methods available which i am not aware of.

**Comment by polidore** [comment]
well, you can copy and paste!

**Comment by dennisv** [comment]
+1 this is keeping me from using zappa in my application

**Comment by twilson63** [comment]
+1

**Comment by namuol** [comment]
Yup, just discovered that I need this, too.

**Comment by chlai88** [comment]
+1 more

**Comment by shimaore** [comment]
This doesn't apply cleanly in zappa 0.3.3 due to commit 24e626c43752e3789bedf0beaeec100b1103c682.

Is this still needed? If so what would be an acceptable solution?

(I was trying to get this integrated into https://github.com/zappajs/zappajs)

**Comment by chrisforbes** [comment]
+1

**Pull request closed without merging**
