### PR TITLE
Updated Express version

### PR DESCRIPTION
**Pull request by tgkokk**
When trying to install Zappa, I run into this error:

`Error: Not found: express@'>=2.4.0- <2.5.0-'`

It turned out that the Express version is outdated, and since no one mentioned it, I decided to pull it myself.

### CODE REVIEW

**Comment by loqur** [comment]
please merge for node 0.6!

**Comment by JasonMiesionczek** [comment]
I'll second that merge request :)

**Comment by ghost** [comment]
Yeah it's funny, haven't seen Maurice around anywhere, even IRC. Wonder if everything is cool...

**Comment by mauricemach** [comment]
Sorry, just been busy with other stuff. v0.3.3 is out and works with newer versions of express and node.

**Pull request closed without merging**
